In [3]:
import numpy as np
import pandas as pd

In [7]:
wt = pd.read_csv('weather.csv')
wt

,w_idx,islandName,baseDate,baseTime,fcstDate,fcstTime,POP,PTY,PCP,REH,...,SKY,TMP,TMN,TMX,UUU,VVV,WAV,VEC,WSD,insertDttm
0,1,신안 반월박지도,20240821,1400,20240821,1500,0,0.0,강수없음,80,...,1,31.0,NaN,NaN,0.8,7.4,0.5,186,7.4,2024-08-21 14:30:05
1,2,고흥 연홍도,20240821,1400,20240821,1500,0,0.0,강수없음,75,...,1,32.0,NaN,NaN,-0.3,7.2,0.5,177,7.2,2024-08-21 14:30:05
2,3,강진 가우도,20240821,1400,20240821,1500,0,0.0,강수없음,70,...,1,33.0,NaN,NaN,1.0,4.0,0.0,194,4.1,2024-08-21 14:30:05
3,4,여수 낭도,20240821,1400,20240821,1500,0,0.0,강수없음,75,...,1,32.0,NaN,NaN,1.0,7.0,0.5,188,7.1,2024-08-21 14:30:05
4,5,진도 금호도,20240821,1400,20240821,1500,0,0.0,강수없음,80,...,1,31.0,NaN,NaN,1.6,6.5,0.0,194,6.7,2024-08-21 14:30:05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25358,25359,완도 금당도,20250105,2300,20250106,0,30,0.0,강수없음,80,...,4,8.0,NaN,NaN,2.6,0.3,0.5,263,2.6,2025-01-05 23:00:01
25359,25360,완도 여서도,20250105,2300,20250106,0,30,0.0,강수없음,75,...,4,8.0,NaN,NaN,4.4,-0.2,0.5,273,4.4,2025-01-05 23:00:01
25360,25361,영광 안마도,20250105,2300,20250106,0,20,0.0,강수없음,80,...,3,8.0,NaN,NaN,2.8,2.0,0.5,234,3.4,2025-01-05 23:00:01
25361,25362,신안 우이도,20250105,2300,20250106,0,20,0.0,강수없음,80,...,3,9.0,NaN,NaN,4.7,0.8,0.5,260,4.8,2025-01-05 23:00:01
25362,25363,여수 손죽도,20250105,2300,20250106,0,30,0.0,강수없음,70,...,4,10.0,NaN,NaN,4.8,-2.2,0.5,295,5.3,2025-01-05 23:00:01