In [ ]:
'''
03_HS01~03 합치기, 중요 키워드 줄이기 
'''

In [2]:
import numpy as np
import pandas as pd

In [25]:
# JSON 데이터 로드
df = pd.read_json('data/감성대화말뭉치(최종데이터)_Training.json')

# # 'profile'과 'talk' 컬럼을 펼치기 (1차 변환)
# df_profile = df['profile'].apply(pd.Series)
# df_talk = df['talk'].apply(pd.Series)

# # 'emotion' 컬럼을 추가로 펼치기
# df_emotion = df_profile['emotion'].apply(pd.Series)

# # 'content' 컬럼을 추가로 펼치기 (대화 내용)
# df_content = df_talk['content'].apply(pd.Series)

# # 필요한 컬럼 선택
# df_cleaned = pd.concat([df_emotion[['type']], df_content], axis=1)
# df_cleaned.rename(columns={'type': 'emotion_type'}, inplace=True)

# # 결과 확인
# import ace_tools_open as tools
# #tools.display_dataframe_to_user(name="감성 대화 데이터", dataframe=df_cleaned)

In [26]:
df.head()

,profile,talk
0,"{'persona-id': 'Pro_05349', 'persona': {'perso...","{'id': {'profile-id': 'Pro_05349', 'talk-id': ..."
1,"{'persona-id': 'Pro_05349', 'persona': {'perso...","{'id': {'profile-id': 'Pro_05349', 'talk-id': ..."
2,"{'persona-id': 'Pro_05349', 'persona': {'perso...","{'id': {'profile-id': 'Pro_05349', 'talk-id': ..."
3,"{'persona-id': 'Pro_05349', 'persona': {'perso...","{'id': {'profile-id': 'Pro_05349', 'talk-id': ..."
4,"{'persona-id': 'Pro_05349', 'persona': {'perso...","{'id': {'profile-id': 'Pro_05349', 'talk-id': ..."

In [32]:
df_profile = df['profile'].apply(pd.Series)
df_profile.head()

,persona-id,persona,emotion
0,Pro_05349,"{'persona-id': 'A02_G02_C01', 'human': ['A02',...","{'emotion-id': 'S06_D02_E18', 'type': 'E18', '..."
1,Pro_05349,"{'persona-id': 'A02_G02_C01', 'human': ['A02',...","{'emotion-id': 'S06_D02_E18', 'type': 'E18', '..."
2,Pro_05349,"{'persona-id': 'A02_G02_C01', 'human': ['A02',...","{'emotion-id': 'S06_D02_E18', 'type': 'E18', '..."
3,Pro_05349,"{'persona-id': 'A02_G02_C01', 'human': ['A02',...","{'emotion-id': 'S06_D02_E18', 'type': 'E18', '..."
4,Pro_05349,"{'persona-id': 'A02_G02_C01', 'human': ['A02',...","{'emotion-id': 'S06_D02_E18', 'type': 'E18', '..."

In [34]:
df_talk = df['talk'].apply(pd.Series)
df_talk.head()

,id,content
0,"{'profile-id': 'Pro_05349', 'talk-id': 'Pro_05...","{'HS01': '일은 왜 해도 해도 끝이 없을까? 화가 난다.', 'SS01': ..."
1,"{'profile-id': 'Pro_05349', 'talk-id': 'Pro_05...",{'HS01': '이번 달에 또 급여가 깎였어! 물가는 오르는데 월급만 자꾸 깎이니...
2,"{'profile-id': 'Pro_05349', 'talk-id': 'Pro_05...",{'HS01': '회사에 신입이 들어왔는데 말투가 거슬려. 그런 애를 매일 봐야 한...
3,"{'profile-id': 'Pro_05349', 'talk-id': 'Pro_05...",{'HS01': '직장에서 막내라는 이유로 나에게만 온갖 심부름을 시켜. 일도 많은...
4,"{'profile-id': 'Pro_05349', 'talk-id': 'Pro_05...",{'HS01': '얼마 전 입사한 신입사원이 나를 무시하는 것 같아서 너무 화가 나...

In [18]:
df_content = df_talk['content'].apply(pd.Series)
print(df_content)

                                                    HS01  \
0                              일은 왜 해도 해도 끝이 없을까? 화가 난다.
1         이번 달에 또 급여가 깎였어! 물가는 오르는데 월급만 자꾸 깎이니까 너무 화가 나.
2      회사에 신입이 들어왔는데 말투가 거슬려. 그런 애를 매일 봐야 한다고 생각하니까 스...
3      직장에서 막내라는 이유로 나에게만 온갖 심부름을 시켜. 일도 많은 데 정말 분하고 ...
4                  얼마 전 입사한 신입사원이 나를 무시하는 것 같아서 너무 화가 나.
...                                                  ...
51623     나이가 먹고 이제 돈도 못 벌어 오니까 어떻게 살아가야 할지 막막해. 능력도 없고.
51624        몸이 많이 약해졌나 봐. 이제 전과 같이 일하지 못할 것 같아 너무 짜증 나.
51625   이제 어떻게 해야 할지 모르겠어. 남편도 그렇고 노후 준비도 안 되어서 미래가 걱정돼.
51626  몇십 년을 함께 살았던 남편과 이혼했어. 그동안의 세월에 배신감을 느끼고 너무 화가 나.
51627  남편과 결혼한 지 사십 년이야. 이제 사람 만나는 것도 버겁고 알던 사람도 점점 사라져.

                                                    SS01  \
0                            많이 힘드시겠어요. 주위에 의논할 상대가 있나요?
1               급여가 줄어 속상하시겠어요. 월급이 줄어든 것을 어떻게 보완하실 건가요?
2      회사 동료 때문에 스트레스를 많이 받는 것 같아요. 문제 해결을 위해 어떤 노력을 ...
3      관련 없는 심부름을 모두 하게 되어서 노여우시군요. 어떤 것이 상황을 나아질 수 있...
4      무시하는 것 같은 태도에 화가 나셨군요. 상대방의 어떤 행동이 그런 감정을 유발하는...
...                                                  ...
51623                 경제적인 문제 때문에 막막하시군요. 마음이 편치 않으시겠어요.
51624              건강에 대한 어려움 때문에 기분이 좋지 않으시군요. 속상하시겠어요.
51625                      노후 준비에 대한 어려움 때문에 걱정이 많으시겠어요.
51626                               가족과의 문제 때문에 속상하시겠어요.
51627                    대인관계에 대한 어려움 때문에 걱정되시고 속상하시겠어요.

                                                    HS02  \
0                    그냥 내가 해결하는 게 나아. 남들한테 부담 주고 싶지도 않고.
1       최대한 지출을 억제해야겠어. 월급이 줄어들었으니 고정지출을 줄일 수밖에 없을 것 같아.
2      잘 안 맞는 사람이랑 억지로 잘 지내는 것보단 조금은 거리를 두고 예의를 갖춰서 대...
3                  직장 사람들과 솔직하게 이야기해보고 싶어. 일하는 데에 방해된다고.
4                    상사인 나에게 먼저 인사하지 않아서 매일 내가 먼저 인사한다고!
...                                                  ...
51623                   아무것도 할 수 없는 내가 무가치하게 느껴지고 실망스러워.
51624          마음 같아서는 다 할 수 있는 일인데 이젠 몸이 안 따라와 주니 화만 나.
51625  주변 사람들은 다 노후 준비도 잘해두었던데 난 어떻게 해야 할지 모르겠어. 막막하기...
51626             이제 할 수 있는 일도 없고 이렇게 힘들게 사는 게 불만스럽기만 해.
51627             사람들을 만나는 것이 어려워. 자꾸 사람들을 의심하게만 되고 말이야.

                                                    SS02  \
0         혼자 해결하기로 했군요. 혼자서 해결하기 힘들면 주위에 의논할 사람을 찾아보세요.
1                               월급이 줄어든 만큼 소비를 줄일 계획이군요.
2              스트레스받지 않기 위해선 인간관계에 있어 약간의 거리를 두는 게 좋겠군요.
3                            직장 사람들과 이야기를 해 보겠다고 결심하셨군요.
4      항상 먼저 인사하게 되어 화가 나셨군요. 어떻게 하면 신입사원에게 화났음을 표현할 ...
...                                                  ...
51623                       지금 할 수 있는 가장 합리적인 행동은 무엇인가요?
51624                      어떻게 하면 지금의 기분을 나아지게 할 수 있을까요?
51625                   지금의 상황에서 할 수 있는 가장 좋은 행동이 무엇일까요?
51626                   지금의 감정을 나아지게 할 수 있는 어떤 방법이 있을까요?
51627                    어떻게 하면 지금의 상황에 변화를 만들어낼 수 있을까요?

                                                    HS03  \
0
1
2
3
4
...                                                  ...
51623                 노년층을 위한 경제적 지원이나 부업 같은 것도 알아보아야겠어.
51624            남편과 함께 게이트볼이나 치러 가야겠어. 그럼 기분이 나아질 것 같아.
51625      남편과 함께 실버 일자리나 노년층을 위한 국가 지원에 대해 자세히 알아보아야겠어.
51626            함께 친하게 지내던 동네 언니 동생들과 빈자리를 조금이나마 채울까 해.
51627  사람들을 볼 때 의심하고 불신하는 마음을 억눌러야겠어. 사람들을 색안경을 끼고 보지...

                                     SS03
0
1
2
3
4
...                                   ...
51623                    좋은 결과 얻으시길 바랄게요.
51624         남편과 함께하는 좋은 외출 시간 되시길 바랄게요.
51625     좋은 정보 많이 얻으셔서 걱정을 좀 덜으셨으면 좋겠어요.
51626             지인분들과 좋은 시간 보내셨으면 좋겠어요.
51627  원하시는 대로 가지고 계시던 걱정이 잘 해결되셨으면 좋겠어요.

[51628 rows x 6 columns]

In [22]:
df_content_concat = pd.Dataframe(df_content[['HS01','HS02','HS03']])
df_content_concat = pd.concat([df_emotion[['type']], df_content], axis=1)
print(df_content_concat.head())

AttributeError: module 'pandas' has no attribute 'dataframe'